//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP321.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public System.DateTime Date_Exam { get; set; }
        public Nullable<int> Id_Subject { get; set; }
        public int Id_Student { get; set; }
        public Nullable<int> Id_Employee { get; set; }
        public string Auditory { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Id_Exam { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
